select * from CUSTOMER_MUST;


select  * from ADDRESS_MUST;

select * from CUSTOMER_MUST inner join ADDRESS_MUST on CUSTOMER_MUST.ADDRESS_ID = ADDRESS_MUST.ADDRESS_ID;



select CUSTOMER_MUST.FIRST_NAME, CUSTOMER_MUST.LAST_NAME,ADDRESS_MUST.ADDRESS,ADDRESS_MUST.PHONE
from CUSTOMER_MUST inner join ADDRESS_MUST on CUSTOMER_MUST.ADDRESS_ID = ADDRESS_MUST.ADDRESS_ID;



select c.FIRST_NAME, c.LAST_NAME,a.ADDRESS,a.PHONE
from CUSTOMER_MUST c inner join ADDRESS_MUST a on c.ADDRESS_ID = a.ADDRESS_ID;